# Generated by Django 2.2 on 2022-04-27 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20220427_1144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='ph_restaurant',
        ),
        migrations.AlterField(
            model_name='delivery',
            name='ph_delivery',
            field=models.CharField(max_length=300),
        ),
    ]
